name: mon-os-ublue
description: Mon image Fedora
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: rpm-ostree
    repos:
      # --- Thèmes (Bibata) ---
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-43/peterwu-rendezvous-fedora-43.repo
      # --- L'écosystème Universal Blue ---
      - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-43/ublue-os-packages-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-43/ublue-os-staging-fedora-43.repo
    remove:
      # ---Les applications GNOME inutiles ---
      - gnome-tour
      - firefox
      - firefox-langpacks
      - gnome-system-monitor
      - toolbox
      - htop
      - nvtop
      - yelp
      - gnome-software
    install:
      # ---Utilitaires de base ---
      - distrobox
      - firewall-config

      # --- Thèmes ---
      - papirus-icon-theme
      - bibata-cursor-themes
      - google-noto-sans-mono-fonts
      - google-noto-emoji-fonts

      # --- L'écosystème Universal Blue ---
      - ublue-brew
      - ublue-fastfetch
      - ublue-bling
      - ublue-os-udev-rules
      - ublue-os-media-automount-udev
      
      # --- Services d'automatisation ---
      - uupd
      - ublue-setup-services

      # --- Gaming ---
      - steam-devices
      - gamescope
      - mangohud

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          # --- Applications GNOME ---
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Logs
          - org.gnome.Maps
          - org.gnome.Weather
          - org.gnome.baobab
          - org.gnome.Papers
          - org.gnome.NautilusPreviewer
          - org.gnome.font-viewer
          - org.gnome.Showtime
          - org.gnome.Lollypop
          - org.gnome.Evolution
          
          # --- Outils système ---
          - io.missioncenter.MissionCenter
          - io.github.kolunmi.Bazaar
          - page.tesk.Refine
          - it.mijorus.gearlever
          - io.github.flattool.Warehouse
          - io.github.flattool.Ignition
          - com.mattjakeman.ExtensionManager
          - com.github.tchx84.Flatseal
          - io.github.ilya_zlobintsev.LACT

          # --- Thèmes ---
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.gtk.Gtk3theme.adw-gtk3

          # --- Virtualisation ---
          - com.ranfdev.DistroShelf
          - org.gnome.Boxes
          
          # --- Applications ---
          - org.signal.Signal
          - org.remmina.Remmina
          - org.raspberrypi.rpi-imager
          - org.onlyoffice.desktopeditors
          - org.gimp.GIMP
          - org.freecad.FreeCAD
          - org.deluge_torrent.deluge
          - net.cozic.joplin_desktop
          - me.proton.Mail
          - io.gitlab.news_flash.NewsFlash
          - io.gitlab.librewolf-community
          - im.riot.Riot
          - com.visualstudio.code
          - com.ultimaker.cura
          - com.spotify.Client
          - com.jeffser.Alpaca
          - com.jeffser.Alpaca.Plugins.AMD
          - com.jeffser.Alpaca.Plugins.Ollama
          - com.google.Chrome
          - com.discordapp.Discord
          - com.bitwarden.desktop

          # --- Gaming ---
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - io.github.Faugus.faugus-launcher
          - com.vysp3r.ProtonPlus
          - io.github.benjamimgois.goverlay
          - org.freedesktop.Platform.VulkanLayer.MangoHud
          - org.freedesktop.Platform.VulkanLayer.vkBasalt

  - type: brew
    auto-update: true        
    update-interval: '6h'     
    auto-upgrade: true       
    upgrade-interval: '1d'     
    brew-analytics: false

  - type: files
    files:
      - source: system
        destination: /

  - type: signing
