name: mon-os-ublue
description: Mon image Fedora
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - fastfetch

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.discordapp.Discord

  - type: signing
