name: mon-os-ublue
description: Mon image Fedora personnalisée avec xpadneo
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: rpm-ostree
remove:
      - gnome-tour
      - firefox
      - firefox-langpacks
      - gnome-system-monitor
      - gnome-terminal
      - gnome-console
      - malcontent
      - toolbox
      
    install:
      - fastfetch

  - type: akmods
    install:
      - xpadneo

  - type: default-flatpaks
    system:
      install:
        - com.mozilla.firefox
        - com.discordapp.Discord

  - type: signing # Toujours garder à la fin !
