name: mon-os-ublue
description: Mon image Fedora
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: rpm-ostree
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks
      - gnome-system-monitor
      - malcontent
      - malcontent-control
      - toolbox
    install:
      - fastfetch

  - type: akmods
    install:
      - xpadneo

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - com.discordapp.Discord

  - type: signing
