name: silverbuild
description: Bazzite - Version optimisée et allégée.
base-image: ghcr.io/ublue-os/bazzite-gnome

modules:
  - type: rpm-ostree
    repos:
      # --- Starship & Thèmes ---
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo

    remove:
      # --- Debloat Virtualisation Guest (Non nécessaire sur PC physique) ---
      - open-vm-tools
      - hyperv-daemons
      - qemu-guest-agent
      - spice-vdagent
      - xorg-x11-drv-vmware
      - xorg-x11-drv-qxl
      - virtualbox-guest-additions
      
      # --- Applications demandées ---
      - yelp                # Aide GNOME
      - gnome-tour          # Bienvenue GNOME
      - Sunshine            # (Bazzite l'inclut par défaut, on le retire ici)
      - waydroid            # (Support Android)

  - type: signing
