name: mon-os-ublue
description: Mon image Fedora
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  - type: rpm-ostree
    remove:
      - gnome-tour
      - gnome-system-monitor
      - toolbox
      - htop
      - nvtop
    install:
      - fastfetch

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - com.discordapp.Discord

  - type: signing
